import {people as seed,relations,personById} from './family-data.js';
let people=[...seed,...JSON.parse(localStorage.getItem('radis-extra')||'[]')];let scale=.88,tx=80,ty=25,drag=false,last={x:0,y:0};
const pos={pedro:[120,100],carlos:[330,100],maria:[520,100],manoel:[740,100],america:[500,255],arlinda:[790,255],zeli:[500,410],terezinha:[790,410],elielton:[450,565],elenilton:[600,565],sheila:[780,565],ritheli:[930,565],joyce:[700,735]};
const $=s=>document.querySelector(s),initials=n=>n.split(' ').slice(0,2).map(x=>x[0]).join('').toUpperCase();
function render(filter=''){const nodes=$('#nodes');nodes.innerHTML='';const q=filter.toLowerCase();people.forEach((p,i)=>{const [x,y]=pos[p.id]||[1080+(i%2)*170,170+Math.floor(i/2)*115];const el=document.createElement('div');el.className=`node ${p.sex==='F'?'f':'m'} ${p.status==='a-confirmar'?'pending':''} ${p.id==='joyce'?'focus':''}`;el.style.left=x+'px';el.style.top=y+'px';if(q&&!`${p.name} ${p.alias||''} ${(p.tags||[]).join(' ')}`.toLowerCase().includes(q))el.style.opacity='.15';el.innerHTML=`<div class="avatar">${initials(p.name)}</div><b>${p.name}</b><small>${p.alias?`“${p.alias}” · `:''}${p.generation||'Família'}</small>${p.status==='a-confirmar'?'<span class="badge">A CONFIRMAR</span>':''}`;el.onclick=()=>openProfile(p);nodes.appendChild(el)});drawLinks();stats()}
function drawLinks(){const svg=$('#links');svg.innerHTML='';relations.forEach(r=>{const a=pos[r.from],b=pos[r.to];if(!a||!b)return;const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('class','line '+(r.type==='partner'?'partner':''));let d;if(r.type==='partner')d=`M${a[0]},${a[1]} C${(a[0]+b[0])/2},${a[1]-35} ${(a[0]+b[0])/2},${b[1]-35} ${b[0]},${b[1]}`;else{const mid=(a[1]+b[1])/2;d=`M${a[0]},${a[1]+30} C${a[0]},${mid} ${b[0]},${mid} ${b[0]},${b[1]-30}`}path.setAttribute('d',d);svg.appendChild(path)})}
function stats(){$('#count').textContent=people.length;$('#pending').textContent=people.filter(p=>p.status==='a-confirmar').length;$('#confirmed').textContent=people.filter(p=>p.status!=='a-confirmar').length}
function openProfile(p){const parents=relations.filter(r=>r.type==='parent'&&r.to===p.id).map(r=>personById(r.from)?.name).filter(Boolean);const kids=relations.filter(r=>r.type==='parent'&&r.from===p.id).map(r=>personById(r.to)?.name).filter(Boolean);$('#profileBody').innerHTML=`<div class="profileTop"><div class="portrait">${initials(p.name)}</div><div><div class="eyebrow">${p.status==='a-confirmar'?'REGISTRO A CONFIRMAR':'REGISTRO FAMILIAR'}</div><h2>${p.name}</h2><p>${p.alias?`Também conhecida como “${p.alias}” · `:''}${p.branch||'Família Radis'}</p></div></div><div class="facts"><div class="fact"><span>Geração</span><span>${p.generation||'—'}</span></div><div class="fact"><span>Nascimento</span><span>${p.birth||'Ainda não registrado'}</span></div><div class="fact"><span>Óbito</span><span>${p.death||'—'}</span></div>${parents.length?`<div class="fact"><span>Ascendência</span><span>${parents.join(' + ')}</span></div>`:''}${kids.length?`<div class="fact"><span>Descendência</span><span>${kids.join(', ')}</span></div>`:''}</div><div class="chips">${(p.tags||[]).map(t=>`<span>${t}</span>`).join('')}</div><div class="notes">${p.notes||'Sem observações registradas.'}</div>`;$('#profile').showModal()}
function transform(){$('#stage').style.transform=`translate(${tx}px,${ty}px) scale(${scale})`};function zoom(d){scale=Math.max(.35,Math.min(1.7,scale+d));transform()}
$('#viewport').onpointerdown=e=>{drag=true;last={x:e.clientX,y:e.clientY};$('#viewport').setPointerCapture(e.pointerId)};$('#viewport').onpointermove=e=>{if(!drag)return;tx+=e.clientX-last.x;ty+=e.clientY-last.y;last={x:e.clientX,y:e.clientY};transform()};$('#viewport').onpointerup=()=>drag=false;$('#viewport').onwheel=e=>{e.preventDefault();zoom(e.deltaY>0?-.08:.08)};$('#zin').onclick=()=>zoom(.12);$('#zout').onclick=()=>zoom(-.12);$('#fit').onclick=()=>{scale=.88;tx=80;ty=25;transform()};$('#search').oninput=e=>render(e.target.value);document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#add').onclick=()=>$('#editor').showModal();
$('#personForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),p={id:'custom-'+Date.now(),name:f.get('name'),sex:f.get('sex'),birth:f.get('birth'),death:f.get('death'),tags:f.get('tags').split(',').map(x=>x.trim()).filter(Boolean),notes:f.get('notes'),generation:'Novo registro',branch:'Radis'};const extras=JSON.parse(localStorage.getItem('radis-extra')||'[]');extras.push(p);localStorage.setItem('radis-extra',JSON.stringify(extras));people.push(p);render();$('#editor').close();e.target.reset()};
$('#export').onclick=()=>{const blob=new Blob([JSON.stringify({people,relations},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='familia-radis-backup.json';a.click();URL.revokeObjectURL(a.href)};
render();transform();
