export const EVIDENCE=['confirmed','family-report','documented','investigate'];
const p=(id,name,sex,generation,notes='',extra={})=>({id,name,sex,branch:'Radis',generation,evidenceStatus:'family-report',tags:[],conditions:[],sources:[],notes,...extra});
export const people=[
p('joyce','Joyce Radis','F','Filhos','Pessoa focal da árvore.',{evidenceStatus:'confirmed'}),p('estevao','Estevão','M','Filhos','Irmão de Joyce.',{evidenceStatus:'confirmed'}),p('arthur','Arthur','M','Filhos','Irmão de Joyce.',{evidenceStatus:'confirmed'}),
p('gabi','Gabi','F','Filhos','Filha de Sheila e Elenilton.'),p('samuel','Samuel','M','Filhos','Filho de Sheila e Elenilton.'),
p('ritheli','Ritheli','F','Pais','Filha de Terezinha e José; casada com Elielton.',{evidenceStatus:'confirmed'}),p('sheila','Sheila','F','Tios','Filha de Terezinha e José; casada com Elenilton.',{evidenceStatus:'confirmed'}),p('elielton','Elielton','M','Pais','Filho de Zeli e Sebastião; casado com Ritheli.',{evidenceStatus:'confirmed'}),p('elenilton','Elenilton','M','Tios','Filho de Zeli e Sebastião; casado com Sheila.',{evidenceStatus:'confirmed'}),p('elenice','Elenice','F','Tios','Filha de Zeli e Sebastião.'),p('welington','Welington','M','Tios','Filho de Zeli e Sebastião.'),
p('zeli','Zeli Radis','F','Avós','Filha de Merca e Pedro; casada com Sebastião.'),p('sebastiao','Sebastião','M','Avós','Casado com Zeli.'),p('terezinha','Terezinha','F','Avós','Filha de Arlinda e Manoel. Primeiro casamento com José; depois casou-se com Brás.'),p('jose','José','M','Avós','Primeiro marido de Terezinha; pai de Ritheli e Sheila.',{deceased:true}),p('bras','Brás','M','Avós','Segundo marido de Terezinha; pai de Brazin, Fabiana e Renata.'),p('brazin','Brazin','M','Tios','Filho de Terezinha e Brás.'),p('fabiana','Fabiana','F','Tios','Filha de Terezinha e Brás.'),p('renata','Renata','F','Tios','Filha de Terezinha e Brás.'),
p('america','América Radis','F','Bisavós','Conhecida como Merca. Irmã de Arlinda; casada com Pedro; teve vários filhos, entre eles Zeli.',{alias:'Merca',deceased:true}),p('pedro','Pedro','M','Bisavós','Irmão de Manoel; casado com Merca; tiveram vários filhos, entre eles Zeli.',{deceased:true}),p('arlinda','Arlinda Radis','F','Bisavós','Irmã de Merca; casada com Manoel; tiveram vários filhos, entre eles Terezinha e Manoel.',{alias:'Vó Arlinda',deceased:true,evidenceStatus:'confirmed'}),p('manoel-avo','Manoel Radis','M','Bisavós','Irmão de Pedro; casado com Arlinda; tiveram vários filhos.',{alias:'Vô Manoel',deceased:true,evidenceStatus:'confirmed'}),p('manoel-tio','Manoel Radis','M','Tios-avós','Filho de Arlinda e Manoel; homônimo do pai.',{alias:'Tio Manoel'}),
p('carlos','Carlos Radis','M','Ancestrais','Vínculo exato ainda não confirmado.',{evidenceStatus:'investigate',tags:['a confirmar']}),p('maria','Maria Bertosse','F','Ancestrais','Grafia e vínculo exato ainda precisam de confirmação.',{evidenceStatus:'investigate',tags:['grafia a confirmar']})];
export const relations=[
{type:'sibling',from:'america',to:'arlinda'},{type:'sibling',from:'pedro',to:'manoel-avo'},
{type:'partner',from:'pedro',to:'america'},{type:'partner',from:'manoel-avo',to:'arlinda'},
{type:'parent',from:'pedro',to:'zeli'},{type:'parent',from:'america',to:'zeli'},
{type:'parent',from:'manoel-avo',to:'terezinha'},{type:'parent',from:'arlinda',to:'terezinha'},{type:'parent',from:'manoel-avo',to:'manoel-tio'},{type:'parent',from:'arlinda',to:'manoel-tio'},
{type:'partner',from:'zeli',to:'sebastiao'},...['elielton','elenilton','elenice','welington'].flatMap(to=>[{type:'parent',from:'zeli',to},{type:'parent',from:'sebastiao',to}]),
{type:'partner',from:'jose',to:'terezinha'},{type:'partner',from:'terezinha',to:'bras'},...['ritheli','sheila'].flatMap(to=>[{type:'parent',from:'terezinha',to},{type:'parent',from:'jose',to}]),...['brazin','fabiana','renata'].flatMap(to=>[{type:'parent',from:'terezinha',to},{type:'parent',from:'bras',to}]),
{type:'partner',from:'ritheli',to:'elielton'},...['joyce','estevao','arthur'].flatMap(to=>[{type:'parent',from:'ritheli',to},{type:'parent',from:'elielton',to}]),
{type:'partner',from:'sheila',to:'elenilton'},...['gabi','samuel'].flatMap(to=>[{type:'parent',from:'sheila',to},{type:'parent',from:'elenilton',to}])];
export const personById=(id,list=people)=>list.find(p=>p.id===id);
export function validateData(list=people,rels=relations){const errors=[];const ids=new Set(list.map(p=>p.id));if(ids.size!==list.length)errors.push('IDs duplicados');for(const p of list)if(!EVIDENCE.includes(p.evidenceStatus||'family-report'))errors.push(`Evidência inválida: ${p.id}`);for(const r of rels)if(!ids.has(r.from)||!ids.has(r.to))errors.push(`Relação inválida: ${r.from} → ${r.to}`);return errors}
