export const unionKey=(a,b)=>[a,b].sort().join('::');
export function buildUnions(relations){const unions=new Map();for(const r of relations.filter(r=>r.type==='partner')){const key=unionKey(r.from,r.to);unions.set(key,{key,partners:[r.from,r.to],children:[]})}const parentsByChild=new Map();for(const r of relations.filter(r=>r.type==='parent')){if(!parentsByChild.has(r.to))parentsByChild.set(r.to,new Set());parentsByChild.get(r.to).add(r.from)}for(const union of unions.values()){const[a,b]=union.partners;for(const[child,parents]of parentsByChild)if(parents.has(a)&&parents.has(b))union.children.push(child)}return unions}
export function buildGraphModel(people,relations){const linked=new Set();for(const r of relations){linked.add(r.from);linked.add(r.to)}return{unions:buildUnions(relations),linked,unconnected:new Set(people.filter(p=>!linked.has(p.id)).map(p=>p.id))}}
export function computeBounds(nodes,ids=[...nodes.keys()]){const boxes=ids.map(id=>nodes.get(id)).filter(Boolean);if(!boxes.length)return{minX:0,minY:0,maxX:1,maxY:1,width:1,height:1};const minX=Math.min(...boxes.map(b=>b.left-b.width/2)),minY=Math.min(...boxes.map(b=>b.top-b.height/2)),maxX=Math.max(...boxes.map(b=>b.left+b.width/2)),maxY=Math.max(...boxes.map(b=>b.top+b.height/2));return{minX,minY,maxX,maxY,width:maxX-minX,height:maxY-minY}}
export function sideAnchors(a,b){const left=a.left<=b.left?a:b,right=a.left<=b.left?b:a;return{left:{x:left.left+left.width/2,y:left.top},right:{x:right.left-right.width/2,y:right.top},midpoint:{x:(left.left+right.left)/2,y:(left.top+right.top)/2}}}
export function bottomAnchor(box){return{x:box.left,y:box.top+box.height/2}}
export function topAnchor(box){return{x:box.left,y:box.top-box.height/2}}
export function interpretWheel({deltaX=0,deltaY=0,ctrlKey=false,metaKey=false}){if(ctrlKey||metaKey){const raw=Math.exp(-deltaY*.004);return{type:'zoom',factor:Math.max(.92,Math.min(1.08,raw))}}return{type:'pan',dx:-deltaX,dy:-deltaY}}
export function isClickGesture({startX,startY,endX,endY},threshold=5){return Math.hypot(endX-startX,endY-startY)<=threshold}
